enum response_message {
    ACCESS_TOKEN_MISSING = 'Access token is missing or expired!',
    INVALID_TOKEN = 'Invalid payload!',
    INTERNAL_ERROR = 'Internal server error!',
    EMAIL_ALREADY_EXIST = "Email already exists!",
    PHONE_ALREADY_EXIST = "Phone number already exists!",
    ALL_REQUIRED = "All fields are required!",
    PASSWORD_NOT_MATCH = "Passwords do not match!",
    USER_REGISTERED = "User registered!",
    INVALID_EMAIL = "Invalid email!",
    INVALID_PASSWORD = "Invalid password!",
    TOKEN_NOT_CREATED = "Couldn't create token!",
    USER_LOGIN = "User logged in!",
    USER_LOGOUT = "Logout successful!",
    REFRESH_TOKEN_MISSING = "Refresh token missing!",
    TOKEN_EXPIRED = "Token expired",
    TOKEN_CREATED='Access token created SuccessFully',
    TOKEN_REFRESHED = "Tokens refreshed!",
    USER_NOT_FOUND = "User not found!",
    USER_DATA = "User data fetched!",
    EMAIL_PASSWORD_REQUIRED = "Email and password are required!",
    SOMETHING_WENT_WRONG = "Some thing went wrong!",
    FETCH_PRODUCT_DATA = "Product data fetched successfully!",
    PRODUCT_ADDED = "Product added successfully!",
    PRODUCT_UPDATED = "Product updated successfully!",
    PRODUCT_DELETED = "Product deleted successfully!",
    PRODUCT_FETCH_ERROR = "Couldn't fetch product!",
    PRODUCT_ADD_ERROR = "Couldn't add product! ",
    PRODUCT_EDIT_ERROR = "COuldn't edit data!",
    PRODUCT_DELETE_ERROR="Couldn't delete product!",
    FETCH_CUSTOMER_DATA = "Customer data fetched successfully!",
    CUSTOMER_ADDED = "Customer added successfully!",
    CUSTOMER_UPDATED = "Customer updated successfully!",
    CUSTOMER_DELETED = "Customer deleted successfully!",
    CUSTOMER_FETCH_ERROR = "Couldn't fetch customer!",
    CUSTOMER_ADD_ERROR = "Couldn't add customer! ",
    CUSTOMER_EDIT_ERROR = "COuldn't edit customer!",
    CUSTOMER_DELETE_ERROR="Couldn't delete customer!",
    PURCHASE_ADD_ERROR="Couldn't add purchase!",
    PURCHASE_ADDED="Purchase added successfully!",
    QUANTITY_UPDATE_ERROR="Couldn't update quantityt!",
    FETCH_ALL_PURCHASE="Fetch all purchase successfully!",
    FETCH_ALL_PURCHASE_ERROR="couldn't fetch all purchase!",
    LOGOUT_SUCCESSFULL="user logout successfully!"
};

export default response_message